version: '2.2.3'
services:
  stripe:
      image: "stripe/stripe-cli:latest"
      network_mode: host
      environment:
          STRIPE_API_KEY:  'rk_test_51KBgUiLkacGjyjdLjgfup6iNy4EP7MbGWAui8a9ohSkXMMen5MuaYHiLuHqBK9ICKcU8rZ7wW8RVxvES2I1wBF3e00CcbzxhGt'
          STRIPE_DEVICE_NAME: 'strype-cli'
      command:
          listen --forward-to localhost:3000/api/webhooks